services:
  - type: web
    name: examen-red-social
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
